Unbounded fetch
terascope/elasticsearch-assets pull request #475
Opened 2020-09-02 17:02 UTC by jsnoble

- all fetchers will now try to pull all records in their given slices to work with active indicies
- spaces_reader_api and elasticsearch_reader_api will fetch window_size from their given index assigned.
- updated api schemas
- updated docs

2020-09-03 20:34 UTC, macgyver603 approved these changes
LGTM

2020-09-03 22:05 UTC, peterdemartini requested changes

2020-09-03 22:05 UTC, peterdemartini commented on asset/src/elasticsearch_reader_api/reader.ts
> +    client: elasticAPI.Client;
We shouldn't be exposing the underlying client.

```suggestion
    protected readonly client: elasticAPI.Client;
```

2020-09-03 22:05 UTC, peterdemartini commented on asset/src/elasticsearch_reader_api/reader.ts
> +    _baseClient: AnyObject;
```suggestion
    private _baseClient: AnyObject;
```

2020-09-03 22:05 UTC, peterdemartini commented on asset/src/elasticsearch_reader_api/reader.ts
> +    constructor(config: ESReaderOptions, client: AnyObject, logger: Logger) {
Why is the client an `AnyObject`?

2020-09-08 19:05 UTC, jsnoble commented on asset/src/elasticsearch_reader_api/reader.ts
> +    async fetch(queryParams: Partial<SlicerDateResults> = {}): Promise<DataEntity[]> {
this method is fetching records for the given slice, naming it something like search felt wrong as we restrict and limit searching to only date range and wildcard searches compared to elasticsearch search function. As for the documentation comment, what do you think is lacking in  ./docs/apis/elasticsearch_reader_api to explain how to use this?

2020-09-08 19:06 UTC, jsnoble commented on asset/src/elasticsearch_reader/elasticsearch_date_range/slicer.ts
> +        const results = await this.api._searchRequest(query);
what are you envision as an abstraction? this is the backdoor we talked about last friday. This is the unsupported api that will most likely change in the future, but allows them to make any search query they want.

2020-09-08 19:22 UTC, peterdemartini commented on asset/src/elasticsearch_reader_api/reader.ts
> +    async fetch(queryParams: Partial<SlicerDateResults> = {}): Promise<DataEntity[]> {
But `fetch` is very generic for something that takes a `SlicerDateResults` as params? I think naming it something like `fetchRange` would be more appropriate? 

It is super useful to have jsdoc's while developing and it is closer to the source of truth (meaning it is easier to keep in sync when making changes), the docs `./docs/apis/elasticsearch_reader_api` should probably be auto-generated from the jsdocs, but for now they should be copied and pasted. (This how most of our libraries operate and it is fairly common among other packages).

2020-09-08 19:23 UTC, peterdemartini commented on asset/src/elasticsearch_reader_api/reader.ts
> +            this.logger.warn(`index: ${this.config.index} is not yet created`);
Not every error throw is going to be a "Index Doesn't Exist" error, we should be more explicit about this check.

2020-09-08 19:31 UTC, peterdemartini commented on asset/src/elasticsearch_reader/elasticsearch_date_range/slicer.ts
> +        const results = await this.api._searchRequest(query);
I think you misinterpreted me, I said *we* shouldn't be using it the lower level API but we can't expose once external developers. I think the whole `getIndexDate` function should be the abstraction.

2020-09-15 15:55 UTC, jsnoble commented
**Elasticsearch API Overview**
### fetch
```(query: ElasticsearchSliceQuery) => Promise<DataEntities[]>```
This will perform an date range or wildcard query to elasticsearch and return the results of the query.

parameters:
- query: an slice query object
  -  start: string, must be paired with end to do a date range query.
  -  end: string, must be paired with start to do a date range query.
  -  wildcard: { field: string, value: string }, an elasticsearch wildcard query on string values. The value needs to be formatted in `key*`,please reference examples below.
  -  key: string, only used for _uid queries on elasticsearch v5 or older. The key need to be specified as `docType#key*` format, please reference examples below.

```js
const dateRangeQuery = {
    start: '2019-04-26T15:00:23.201Z',
    end: '2019-04-26T15:20:23.220Z',
};

let results = await api.fetch(dateRangeQuery);
results === [ { some: 'record', created: '2019-04-26T15:10:23.220Z' }]

const oldUIDQuery = {
   key:  `events#ba*`
};

let results = await api.fetch(oldUIDQuery);
results === [ { some: 'record', created: '2019-04-26T15:10:23.220Z' }]

const wildcardQuery = {
    field: 'uuid,
    value: 'afe1*',
};

let results = await api.fetch(wildcardQuery);
results === [ { some: 'record', uuid: 'afe18550-0081-453f-9e80-93a90782a5bd' }]
```


### count
```(query: ElasticsearchQuery) => Promise<number>```
This will perform an count query and return the number of records in that are in the range of the query.

parameters:
- query: an slice query object
  -  start: string, must be paired with end to do a date range query.
  -  end: string, must be paired with start to do a date range query.
  -  wildcard: { field: string, value: string }, an elasticsearch wildcard query on string values. The value needs to be formatted in `key*`,please reference examples below.
  -  key: string, only used for _uid queries on elasticsearch v5 or older. The key need to be specified as `docType#key*` format, please reference examples below.

```js
const dateRangeQuery = {
    start: '2019-04-26T15:00:23.201Z',
    end: '2019-04-26T15:20:23.220Z',
};

let results = await api.count(dateRangeQuery);
results === 122

const oldUIDQuery = {
   key:  `events#ba*`
};

let results = await api.fetch(oldUIDQuery);
results === 3552

const wildcardQuery = {
    field: 'uuid,
    value: 'afe1*',
};

let results = await api.fetch(wildcardQuery);
results === 1232
```

### _searchRequest
```(query: ElasticsearchSearchParams) => Promise<DataEntities[]>```
This will allow you to pass in a whole elasticsearch query object to make custom queries. THIS IS AN UNSUPPORTED ESCAPE HATCH. Please do not overly rely on this as this is an internal api and will most likely change.

parameters:
- query: an elasticsearch query object

```js
const query: {
    q: '(test:query OR other:thing AND bytes:>=2000)',
    size: 100,
    fields: 'foo,bar,date'
};

const results = await api._searchRequest(query);

api.version === 6
```

### version
```() => number```
This returns the major elasticsearch version that this client is connected to

```js
api.version === 6
```

### verifyIndex
```() => Promise<void>```
This check if the index exists and throw otherwise, this will also log the window_size of that given index.

```js
try {
    await api.verifyIndex()
} catch(err) {
    // handle error or create index because it does not exists or is not available
}
```

### determineSliceInterval
```(interval: string|duration, dateRange?: DateSegments) => Promise<[number, "time unit"]>```

This is a helper api that will determine how big the slice interval should be for your date_slicer, this is already handled in `makeDateSlicer` for you. If you are constructing your own slicer you can use this to help determine the appropriate size. If interval is set to `auto`, dateRange must be provided and the function will calculate and interval for you. If passed in a duration, it will parse it for you in the format listed by the `time_resolution` configuration.

parameters:
- interval: a duration string (ie. `5min`, `30s`, `750ms`), or it may be set to `auto`
- dateRange: optional, only used when interval is set to `auto`,
  - start: a start date
  - limit: the end date


```js
const apiConfig = {
    time_resolution: 'ms'
}

const interval = await api.determineSliceInterval('2s');
interval === [2000, 'ms'];


const dateRange = {
    start: '2019-04-26T15:00:23.201Z',
    limit: '2019-04-26T15:20:23.220Z',
};

const interval = await api.determineSliceInterval('auto', dateRange);
interval === [2763533, 'ms'];
```

### makeDateSlicer
```(args: DateSlicerArgs) => Promise<SlicerFn>```

This function will generate a slicer which is the elasticsearch_reader slicer core component. You can use this to generate slice chunks for your reader.

parameters:
- args: an slice query object
  -  lifecycle: must be set to `once` or `persistent`.
  -  slicerID: the numerical id of the slicer.
  -  numOfSlicers: the number of total slicers that will be generated
  -  recoveryData?: the `SlicerRecoveryData` for the job
  -  windowState?: the windowState controller, *only needed in persistent mode*
  -  startTime?: the start time of the operation, *only needed in persistent mode*
  -  hook?: an optional async callback that you can provide to handle the updates that the slicer creates (start/end times of the index, the interval for the job etc)

Once mode configuration
```js
const lifecycle = 'once';
const numOfSlicers = 3;
const slicerID = 0;
const recoveryData = [];

const hook = async (params) => {
    // params: { interval: [number, "time unit"], start: Date, end: Date}
  console.log(`Final job configuration ${JSON.stringify(params)}`)
};

const slicerConfig: DateSlicerArgs = {
   lifecycle,
   numOfSlicers,
   slicerID,
   recoveryData,
   hook,
};

const slicer = await this.api.makeDateSlicer(slicerConfig);

const results = await slicer();
results === {
    start: '2019-04-26T15:00:23.201Z',
    end: '2019-04-26T16:00:23.201Z',
    limit: '2019-04-26T15:20:23.220Z',
    count: 3467
}
```

Persistent mode configuration
```js
const lifecycle = 'persistent';
const numOfSlicers = 3;
const slicerID = 0;
const recoveryData = [];
const startTime = new Date().toISOString();
const windowState = this.api.makeWindowState(slicers);

const slicerConfig: DateSlicerArgs = {
   lifecycle,
   numOfSlicers,
   slicerID,
   recoveryData,
   startTime,
   windowState
};

const slicer = await this.api.makeDateSlicer(slicerConfig);

const results = await slicer();

results === {
    start: '2019-04-26T15:00:23.201Z',
    end: '2019-04-26T16:00:23.201Z',
    limit: '2019-04-26T15:20:23.220Z',
    count: 3467
}
```

### makeIDSlicer
```(args: IDSlicerArgs) => Promise<SlicerFn>```

This function will generate a slicer which is the id_reader slicer core component. You can use this to generate slice chunks for your reader.

parameters:
- args: an slice query object
  -  lifecycle: must be set to `once` or `persistent`.
  -  slicerID: the numerical id of the slicer.
  -  numOfSlicers: the number of total slicers that will be generated
  -  recoveryData?: the `SlicerRecoveryData` for the job
  -  key_type: The type of id used in index or the chars contained in the field'
  -  key_range?: if provided, slicer will only recurse on these given keys
  -  starting_key_depth: the length of the key generated before attempting to count the records in the index


```js
const lifecycle = 'once';
const numOfSlicers = 3;
const slicerID = 0;
const recoveryData = [];
const key_type = 'hexadecimal';
const starting_key_depth = 2;

const args: IDSlicerArgs = {
    lifecycle,
    numOfSlicers,
    slicerID,
    recoveryData,
    key_type,
    starting_key_depth,
};

const slicer = await this.api.makeIDSlicer(args);

const results = await slicer();
results ===  { key: 'a0*', count: 5 }
```
### determineDateRanges
```(args: IDSlicerArgs) => Promise<{ start: moment.Moment; limit: moment.Moment; }>```

This is a helper api to parse the  [...]

2020-09-15 19:42 UTC, peterdemartini approved these changes
Looks much better, the reader api is still missing jsdocs but I am not going to block it because of it. We **really** do need to be better about using jsdoc in our exposed APIs

2020-09-15 19:43 UTC, kstaken commented
API looks good in general. docs have some detail issues copy and pasted in a few places so problematic. 

backticks

```
const oldUIDQuery = {
   key:  `events#ba*`
};
```

missing quote

```
const wildcardQuery = {
    field: 'uuid,
    value: 'afe1*',
};
```

2020-09-15 23:36 UTC, merged